# Generated by Django 4.2.23 on 2025-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0003_alter_lemma_language_alter_sentence_language_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('language', 'form', 'lemma'), name='unique_word'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(condition=models.Q(('lemma__isnull', True)), fields=('language', 'form'), name='unique_word_without_lemma'),
        ),
    ]
