# Generated by Django 4.2.23 on 2025-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0005_alter_lemma_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.ManyToManyField(blank=True, null=True, to='eleri.sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='eleri.word'),
        ),
    ]
