# Generated by Django 4.2.23 on 2025-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0006_alter_sentence_translation_alter_sentence_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.ManyToManyField(blank=True, to='eleri.sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(blank=True, to='eleri.word'),
        ),
    ]
