# Generated by Django 4.2.23 on 2025-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0007_alter_sentence_text_alter_sentence_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
