# Generated by Django 4.2.23 on 2025-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0008_alter_sentence_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
