# Generated by Django 4.2.23 on 2025-12-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0009_alter_sentence_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='translation',
            new_name='translations',
        ),
    ]
