# Generated by Django 4.2.23 on 2025-12-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0010_rename_translation_sentence_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.CharField(default='gpt-4.1', max_length=100),
            preserve_default=False,
        ),
    ]
