# Generated by Django 4.2.23 on 2025-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0011_sentence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='frequency',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
