# Generated by Django 4.2.23 on 2025-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0012_lemma_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='frequency',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
