# Generated by Django 4.2.23 on 2025-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0013_alter_lemma_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(default='parole_freq', max_length=100),
            preserve_default=False,
        ),
    ]
