# Generated by Django 4.2.23 on 2025-12-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='language',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='words',
        ),
        migrations.AlterUniqueTogether(
            name='phrasetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='source_phrase',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='target_phrase',
        ),
        migrations.AlterUniqueTogether(
            name='translationvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translationvariant',
            name='source_word',
        ),
        migrations.RemoveField(
            model_name='translationvariant',
            name='target_word',
        ),
        migrations.RemoveIndex(
            model_name='word',
            name='eleri_word_frequen_75f201_idx',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.DeleteModel(
            name='PhraseTranslation',
        ),
        migrations.DeleteModel(
            name='TranslationVariant',
        ),
        migrations.AddField(
            model_name='sentence',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleri.language'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translation',
            field=models.ManyToManyField(to='eleri.sentence'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(to='eleri.word'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleri.language'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='sense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleri.sense'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleri.lemma'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('language', 'form', 'lemma')},
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('language', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='lemma',
            unique_together={('language', 'headword', 'sense')},
        ),
    ]
