# Generated by Django 4.2.23 on 2025-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleri', '0004_alter_word_unique_together_word_unique_word_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lemma',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lemma',
            constraint=models.UniqueConstraint(fields=('language', 'headword', 'sense'), name='unique_lemma'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('language', 'text'), name='unique_sentence'),
        ),
    ]
