'''
Admin module for Eleri application.

Contains a custom admin interface for Sentence model. Everything else is
autogenerated.
'''

from django.apps import apps
from django.contrib import admin
from .models import Sentence


class SentenceAdmin(admin.ModelAdmin):
    '''
    Custom admin interface for Sentence model.

    The interface allows selecting and editing word and translation
    relationships using raw IDs instead of dropdowns. This is useful when
    dealing with large amounts of data.

    Attributes:
        raw_id_fields (tuple): A tuple of field names that should be displayed
            as raw IDs in the admin interface.
    '''

    raw_id_fields = ('words', 'translations')


admin.site.register(Sentence, SentenceAdmin)
for model in apps.get_app_config(__package__.split('.')[0]).get_models():
    if not admin.site.is_registered(model):
        admin.site.register(model)
